# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alok Ranjan
email: alok2@illinois.edu
description: PhD Candidate
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alokranjan06.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: 
linkedin_username: 
scholar_username: 
orcid_username: 

# Google Analytics
google_analytics: 


# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Extras
mathjax: true
